// src/components/layout/TopNav.jsx
﻿import { NavLink } from 'react-router-dom';
import { useState } from 'react';

export default function TopNav({
  isAuthenticated,
  isDark,
  guestLinks,
  authLinks,
  onLogin,
  onTrial,
  onCabinet,
  onHome,
  onToggleTheme,
}) {
  const [menuOpen, setMenuOpen] = useState(false);

  const goHome = () => {
    onHome();
    setMenuOpen(false);
  };

  const closeMenu = () => setMenuOpen(false);

  return (
    <header className={`top-nav ${menuOpen ? 'menu-open' : ''}`}>
      <div className="nav-left">
        <button className="logo" type="button" onClick={goHome}>
          <span className="logo-mark">ML</span>
          <span className="logo-text">MoneyLens</span>
        </button>
        <button className="menu-toggle" type="button" onClick={() => setMenuOpen((v) => !v)} aria-label="Переключить меню">
          <span>{menuOpen ? 'x' : '='}</span>
        </button>
      </div>

      {!isAuthenticated ? (
        <nav className={`nav-links ${menuOpen ? 'open' : ''}`}>
          {guestLinks.map((link) => (
            <a key={link.label} href={link.href} onClick={closeMenu}>
              {link.label}
            </a>
          ))}
        </nav>
      ) : (
        <nav className={`nav-links ${menuOpen ? 'open' : ''}`} onClick={closeMenu}>
          {authLinks.map((link) => (
            <NavLink key={link.label} to={link.to} className={({ isActive }) => (isActive ? 'active' : '')}>
              {link.label}
            </NavLink>
          ))}
        </nav>
      )}

      <div className={`nav-actions ${menuOpen ? 'open' : ''}`}>
        {!isAuthenticated ? (
          <>
            <button
              className="ghost"
              onClick={() => {
                onLogin();
                closeMenu();
              }}
            >
              Войти
            </button>
            <button
              className="primary"
              onClick={() => {
                onTrial();
                closeMenu();
              }}
            >
              Регистрация
            </button>
          </>
        ) : (
          <button
            className="primary"
            onClick={() => {
              onCabinet();
              closeMenu();
            }}
          >
            Личный кабинет
          </button>
        )}
        <button
          className="ghost theme-toggle"
          title={isDark ? 'Переключить на светлую тему' : 'Переключить на тёмную тему'}
          aria-label={isDark ? 'Светлая тема' : 'Тёмная тема'}
          onClick={onToggleTheme}
        >
          <span aria-hidden="true">{isDark ? '?' : '?'}</span>
        </button>
      </div>
    </header>
  );
}

// src/components/layout/TopNav.vue
<script setup>
import { computed, ref } from 'vue';
import { useRoute, useRouter, RouterLink } from 'vue-router';

const props = defineProps({
  isAuthenticated: { type: Boolean, default: false },
  guestLinks: { type: Array, default: () => [] },
  authLinks: { type: Array, default: () => [] },
});

const emit = defineEmits(['login', 'trial', 'signup', 'cabinet', 'home', 'toggle-theme']);

const route = useRoute();
const router = useRouter();
const menuOpen = ref(false);

const isLanding = computed(() => route.name === 'landing');

function goHome() {
  if (isLanding.value) {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  } else {
    router.push({ name: 'landing' });
  }
  emit('home');
  menuOpen.value = false;
}

function toggleMenu() {
  menuOpen.value = !menuOpen.value;
}

function closeMenu() {
  menuOpen.value = false;
}
</script>

<template>
  <header class="top-nav" :class="{ 'menu-open': menuOpen }">
    <div class="nav-left">
      <button class="logo" type="button" @click="goHome">
        <span class="logo-mark">ML</span>
        <span class="logo-text">MoneyLens</span>
      </button>
      <button class="menu-toggle" type="button" @click="toggleMenu" aria-label="Переключить меню">
        <span v-if="!menuOpen">☰</span>
        <span v-else>✕</span>
      </button>
    </div>

    <nav class="nav-links" v-if="!isAuthenticated" :class="{ open: menuOpen }">
      <a v-for="link in guestLinks" :key="link.label" :href="link.href" @click="closeMenu">
        {{ link.label }}
      </a>
    </nav>
    <nav class="nav-links" v-else :class="{ open: menuOpen }" @click="closeMenu">
      <RouterLink
        v-for="link in authLinks"
        :key="link.label"
        :to="link.to"
        :class="{ active: route.name === link.name }"
      >
        {{ link.label }}
      </RouterLink>
    </nav>

    <div class="nav-actions" :class="{ open: menuOpen }">
      <template v-if="!isAuthenticated">
        <button class="ghost" @click="emit('login'); closeMenu()">Войти</button>
        <button class="primary" @click="emit('trial'); closeMenu()">Регистрация</button>
      </template>
      <template v-else>
        <button class="primary" @click="emit('cabinet'); closeMenu()">Личный кабинет</button>
      </template>
      <button class="ghost" title="Переключить тему" @click="emit('toggle-theme')">🌗</button>
    </div>
  </header>
</template>
