// src/pages/CookiesPage.jsx
﻿export default function CookiesPage() {
  return (
    <main className="content">
      <section className="section-head">
        <p className="pill">Документ</p>
        <h2>Политика cookies MoneyLens</h2>
        <p className="muted">Как мы используем файлы cookies и как вы можете управлять ими.</p>
      </section>

      <div className="panel">
        <h3>1. Какие cookies используются</h3>
        <p className="muted">Сессионные, функциональные и аналитические cookies для корректной работы сервиса.</p>
      </div>

      <div className="panel">
        <h3>2. Как управлять cookies</h3>
        <p className="muted">Вы можете удалить cookies или ограничить их в настройках браузера.</p>
      </div>
    </main>
  );
}

// src/pages/CookiesPage.vue
<template>
  <main class="content">
    <section class="section-head">
      <p class="pill">Документ</p>
      <h2>Политика cookies MoneyLens</h2>
      <p class="muted">Как мы используем файлы cookies и как вы можете управлять ими.</p>
    </section>

    <div class="panel">
      <h3>1. Что такое cookies</h3>
      <p class="muted">
        Cookies — небольшие файлы, которые сохраняются в браузере для корректной работы авторизации и персонализации
        интерфейса.
      </p>
    </div>

    <div class="panel">
      <h3>2. Какие cookies мы используем</h3>
      <ul class="muted">
        <li>Сессионные — для авторизации и сохранения вашего логина.</li>
        <li>Функциональные — чтобы помнить выбранную тему, язык и настройки дашборда.</li>
        <li>Аналитические — агрегированная статистика для улучшения сервиса (без идентификации личности).</li>
      </ul>
    </div>

    <div class="panel">
      <h3>3. Как управлять cookies</h3>
      <p class="muted">
        Вы можете удалить cookies или запретить их в настройках браузера. Учтите, что без сессионных cookies вход может
        быть недоступен.
      </p>
    </div>

    <div class="panel">
      <h3>4. Контакты</h3>
      <p class="muted">
        Вопросы о cookies: <a href="mailto:privacy@moneylens.app">privacy@moneylens.app</a>.
      </p>
    </div>
  </main>
</template>
