// src/pages/PrivacyPage.vue
<template>
  <main class="content">
    <section class="section-head">
      <p class="pill">Документ</p>
      <h2>Политика конфиденциальности MoneyLens</h2>
      <p class="muted">
        Рассказываем, какие данные мы собираем, зачем используем и как защищаем вашу информацию.
      </p>
    </section>

    <div class="panel">
      <h3>1. Какие данные мы обрабатываем</h3>
      <ul class="muted">
        <li>Учётные данные: логин, пароль, контактные данные, указанные в профиле.</li>
        <li>Финансовые записи, которые вы добавляете: операции, цели, бюджеты, счета.</li>
        <li>Технические метаданные: время входа, тип устройства, cookies для сохранения сессии.</li>
      </ul>
    </div>

    <div class="panel">
      <h3>2. Для чего используются данные</h3>
      <p class="muted">
        Данные нужны, чтобы показывать вам дашборд, синхронизировать операции между устройствами и отправлять сервисные
        уведомления. Мы не продаём данные третьим лицам и применяем их только для работы сервиса.
      </p>
    </div>

    <div class="panel">
      <h3>3. Хранение и безопасность</h3>
      <p class="muted">
        Пользовательские файлы хранятся на сервере MoneyLens. Мы применяем шифрование при передаче данных (HTTPS) и
        регулярно делаем резервные копии. Пароли сохраняются только в хэшированном виде.
      </p>
    </div>

    <div class="panel">
      <h3>4. Права пользователя</h3>
      <ul class="muted">
        <li>Запросить копию данных, исправить или удалить профиль.</li>
        <li>Отозвать согласие на обработку, закрыв аккаунт в разделе «Профиль».</li>
        <li>Настроить cookies или очистить их в браузере.</li>
      </ul>
    </div>

    <div class="panel">
      <h3>5. Контакты по вопросам данных</h3>
      <p class="muted">
        Пишите на <a href="mailto:privacy@moneylens.app">privacy@moneylens.app</a> или в поддержку внутри приложения.
      </p>
    </div>
  </main>
</template>

// src/pages/PrivacyPage.jsx
﻿export default function PrivacyPage() {
  return (
    <main className="content">
      <section className="section-head">
        <p className="pill">Документ</p>
        <h2>Политика конфиденциальности MoneyLens</h2>
        <p className="muted">Рассказываем, какие данные собираем, зачем используем и как защищаем вашу информацию.</p>
      </section>

      <div className="panel">
        <h3>1. Какие данные мы обрабатываем</h3>
        <p className="muted">Учетные данные, финансовые записи, цели, бюджеты и технические метаданные сессии.</p>
      </div>

      <div className="panel">
        <h3>2. Для чего используются данные</h3>
        <p className="muted">Для работы дашборда, синхронизации операций и поддержки ваших запросов.</p>
      </div>

      <div className="panel">
        <h3>3. Хранение и безопасность</h3>
        <p className="muted">Передача данных защищена, используются резервные копии и контроль доступа.</p>
      </div>
    </main>
  );
}
