// src/pages/TermsPage.vue
<template>
  <main class="content">
    <section class="section-head">
      <p class="pill">Документ</p>
      <h2>Пользовательское соглашение MoneyLens</h2>
      <p class="muted">Условия использования сервиса и обязательства сторон.</p>
    </section>

    <div class="panel">
      <h3>1. Общие положения</h3>
      <p class="muted">
        Настоящее соглашение регулирует доступ и использование MoneyLens. Регистрируясь, вы подтверждаете, что ознакомлены
        и принимаете условия.
      </p>
    </div>

    <div class="panel">
      <h3>2. Аккаунт и безопасность</h3>
      <ul class="muted">
        <li>Вы отвечаете за сохранность логина и пароля.</li>
        <li>Мы вправе приостановить доступ при нарушении безопасности или правил.</li>
      </ul>
    </div>

    <div class="panel">
      <h3>3. Данные и контент</h3>
      <p class="muted">
        Вы сохраняете права на добавленные данные. Передавая их в сервис, вы предоставляете невозвратную лицензию на
        обработку исключительно для работы функций MoneyLens.
      </p>
    </div>

    <div class="panel">
      <h3>4. Ограничения</h3>
      <ul class="muted">
        <li>Запрещено использовать сервис для противоправных действий и спама.</li>
        <li>Нельзя пытаться взламывать, деобфусцировать или обходить защиту.</li>
      </ul>
    </div>

    <div class="panel">
      <h3>5. Ответственность</h3>
      <p class="muted">
        Сервис предоставляется «как есть». Мы стремимся обеспечить доступность, но не гарантируем отсутствие сбоев.
        Денежные решения вы принимаете самостоятельно.
      </p>
    </div>

    <div class="panel">
      <h3>6. Связь и изменения</h3>
      <p class="muted">
        Обновления соглашения публикуются на этой странице. Вопросы — на <a href="mailto:legal@moneylens.app">legal@moneylens.app</a>.
      </p>
    </div>
  </main>
</template>

// src/pages/TermsPage.jsx
﻿export default function TermsPage() {
  return (
    <main className="content">
      <section className="section-head">
        <p className="pill">Документ</p>
        <h2>Пользовательское соглашение MoneyLens</h2>
        <p className="muted">Условия использования сервиса и обязательства сторон.</p>
      </section>

      <div className="panel">
        <h3>1. Общие положения</h3>
        <p className="muted">Регистрируясь, вы подтверждаете согласие с правилами использования сервиса.</p>
      </div>

      <div className="panel">
        <h3>2. Аккаунт и безопасность</h3>
        <p className="muted">Пользователь отвечает за сохранность логина и пароля.</p>
      </div>

      <div className="panel">
        <h3>3. Ответственность</h3>
        <p className="muted">Сервис предоставляется «как есть», финансовые решения пользователь принимает самостоятельно.</p>
      </div>
    </main>
  );
}
